[sqlfluff]
verbose = 0
nocolor = True
dialect = mariadb

# Turn off large file skipping (process all files)
large_file_skip_byte_limit = 0
large_file_skip_char_limit = 0

# https://docs.sqlfluff.com/en/3.2.4/configuration/ignoring_configuration.html#sqlfluffignore
# ignore failing at parsing more complex things like CREATE PROCEDURE
ignore = parsing

exclude_rules = layout.long_lines,layout.keyword_newline
